/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author cjcor
 */
public class AssignedValueDialog extends javax.swing.JDialog {

    public static String valor;

    /**
     * Creates new form AssignedValueDialog
     */
    public AssignedValueDialog(java.awt.Frame parent, boolean modal, String character) {
        super(parent, modal);
        initComponents();
        lbCharacter.setText(character);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAssigned = new javax.swing.JButton();
        tfValor = new javax.swing.JTextField();
        lbCharacter = new javax.swing.JLabel();
        lbError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Valor");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAssigned.setBackground(new java.awt.Color(102, 102, 255));
        btAssigned.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btAssigned.setForeground(new java.awt.Color(255, 255, 255));
        btAssigned.setText("Asignar Valor");
        btAssigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAssignedActionPerformed(evt);
            }
        });
        jPanel1.add(btAssigned, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        tfValor.setBackground(new java.awt.Color(255, 255, 255));
        tfValor.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        tfValor.setForeground(new java.awt.Color(0, 0, 0));
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });
        tfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfValorKeyReleased(evt);
            }
        });
        jPanel1.add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));

        lbCharacter.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbCharacter.setForeground(new java.awt.Color(0, 0, 0));
        lbCharacter.setText("A");
        jPanel1.add(lbCharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 25, 30));

        lbError.setBackground(new java.awt.Color(204, 204, 204));
        lbError.setFont(new java.awt.Font("Roboto Light", 0, 10)); // NOI18N
        lbError.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(lbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String showMessageDialog(java.awt.Frame parent, String message) {
        AssignedValueDialog msj = new AssignedValueDialog(parent, true, message + ":");
        msj.setVisible(true);
        return valor;
    }
    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed

    }//GEN-LAST:event_tfValorActionPerformed

    private void btAssignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAssignedActionPerformed
        valor = tfValor.getText();
        if (!valor.matches(("[0-9]*"))) {
            lbError.setText("Caracteres invalidos");
        }else if(valor.equals("")){
            lbError.setText("Valor Null");
        }
        else{
            dispose();
        }
    }//GEN-LAST:event_btAssignedActionPerformed

    private void tfValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorKeyReleased
        lbError.setText("");
    }//GEN-LAST:event_tfValorKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAssigned;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCharacter;
    private javax.swing.JLabel lbError;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
